// src/PersonalProgressDashboard.Web/ClientApp/components/Goals.tsx
import * as React from 'react';
import { RouteComponentProps } from 'react-router';
import 'isomorphic-fetch';
import axios from "axios/index";


interface IGoals {
    goals: IGoal[]
}

interface IGoal {
    id: number;
    goalText: string;
    achieveByDate: Date;
    achievedDate: Date;
    isAchieved:boolean;
}


export class MyGoals extends React.Component<RouteComponentProps<{}>, IGoals> {
    isSubmitted: boolean = false;
    val: string;
    constructor() {
        super();
        this.state = {goals:[]}
        axios({
            method: 'get',
            //url: 'http://personal-progress-dashboard-api.azurewebsites.net/api/PersonalGoals'
            url: 'http://localhost:5000/api/PersonalGoals'
        }).then(response => {
            console.log(response.data);
            this.setState({
                goals: response.data
            });
        });
    }
    private static renderGoals(goals: IGoal[]) {
        return <div>
            {goals.map(goal =>
                <dl className="dl-horizontal" key={goal.id}>
                    <dt>My goal is to</dt>
                    <dd>{goal.goalText}</dd>
                    <dt>I want to achieve this by</dt>
                    <dd>{goal.achieveByDate}</dd>
                    <dt>I have achieved this on</dt>
                    <dd>{ goal.isAchieved ?goal.achievedDate : "-"}</dd>
                   
                           </dl>
                       )
                   }
               </div >;

    }
    public render() {
        let goals = MyGoals.renderGoals(this.state.goals);
        return (
            
            <div>{goals}</div>
            );
    }

}

// src/PersonalProgressDashboard.web.Angular/ClientApp/app/components/goals/goals.component.ts
import { Component, Inject } from '@angular/core';
import { Http } from '@angular/http';
import { Goal } from '../../models/goalmodel'

@Component({
    selector: 'goals',
    templateUrl: './goals.component.html'
})
export class GoalsComponent {
    public goals: Goal[];

    constructor(http: Http, @Inject('BASE_URL') baseUrl: string) {
        http.get('http://localhost:53330/api/PersonalGoals').subscribe(result => {
            console.log(result);
            this.goals = result.json() as Goal[];
        }, error => console.error(error));
    }
}


//http://personal-progress-dashboard-api.azurewebsites.net/api/PersonalGoals
//http://localhost:53330/api/PersonalGoals
<h1>My Goals</h1>

<p *ngIf="!goals"><em>Loading...</em></p>

<table class='table' *ngIf="goals">
    <thead>
        <tr>
            <th>Goal</th>
            <th>Achieve By</th>
            <th>Achieved on</th>
            <th>Is Achieved</th>
        </tr>
    </thead>
    <tbody>
        <tr *ngFor="let goal of goals">
            <td>{{ goal.goalText }}</td>
            <td>{{ goal.achieveByDate |  date:'MM/dd/yyyy' }}</td>
            <td>{{ goal.achievedDate |  date:'MM/dd/yyyy'}}</td>
            <td>{{ goal.isAchieved }}</td>
        </tr>
    </tbody>
</table>
